AUTHORITY_MAPPING = {
    "CUSTODIAN_CA_FED": ["TBS", "RCMP", "CSE"],
    "CUSTODIAN_CA_DEFENCE": ["DND", "CSE"],
    "CUSTODIAN_CA_PRIVACY": ["OPC"],
    "CUSTODIAN_QC": ["CAI"],
    "CUSTODIAN_INDIGENOUS": ["FN_OCAP"],
}
